### PR TITLE
Auto import component in script when completion in template

### LINKED ISSUE #684: Auto-import component in <script> when using component in template/javascript
Similar to JS/TS's auto import in VS Code: https://code.visualstudio.com/updates/v1_18#_auto-import-for-javascript-and-typescript

### PR DESCRIPTION
**Pull request by yoyo930021**
Fixed #684 

- [x] add e2e test

### CODE REVIEW

**Comment by Aningaaq** [comment]
When is this fix being released? I'm desperate for some auto imports

**Comment by yoyo930021** [comment]
> When is this fix being released? I'm desperate for some auto imports

**Comment by yoyo930021** [comment]
> When is this fix being released? I'm desperate for some auto imports

It will release when I solve https://github.com/vuejs/vetur/issues/2453 .

**Comment by tuan-lm** [comment]
I sorry if this is a really silly question, but how is this import feature suppose to work ?

When i type in the template it said something about import

Screenshot 2020-11-12 133244

But after i hit `Enter `and then save. Nothing happend

Screenshot 2020-11-12 102443

This is what i expect( the error is because i enable template validate and missing 1 required prop)

Screenshot 2020-11-12 133711

Am i suppose to do something more for it to be able to auto import ?

**Comment by yoyo930021** [comment]
> I sorry if this is a really silly question, but how is this import feature suppose to work ?
> 
> When i type in the template it said something about import
> 
> Screenshot 2020-11-12 133244
> 
> But after i hit `Enter `and then save. Nothing happend
> 
> Screenshot 2020-11-12 102443
> 
> This is what i expect( the error is because i enable template validate and missing 1 required prop)
> 
> Screenshot 2020-11-12 133711
> 
> Am i suppose to do something more for it to be able to auto import ?

You can open a new issue.
and we need to get `button-common` component code.
we need to know the reason for not module in typescript.

**Pull request merged**
