### PR TITLE
Pass version in new template sourceFile for ts perf

### LINKED ISSUE #1731: Validate ts/js on manually on key shortcut
- Vetur version: 0.23.0
- VSCode Version: 1.43.0-insider
- OS Version: Darwin x64 19.3.0 (OsX Catalina 10.15.3)

## Problem

Intellisense popup is a bit slow (2-3 seconds) if i have `vetur.validation.script` on.

It would be nice if I could disable `vetur.validation.script: false` and use key shortcut to manually run js/ts validation.

Could you add an action to manually run js/ts validation?

### LINKED ISSUE #2163: Intellisense in latest Vetur is painfully slow
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.26.1
- VS Code version: 1.48.0

## Problem

Intellisense, e.g. when typing `import whatever from './'` i takes around 10 seconds for suggestion to pop up.

I've tried downgrading VS Code to no avail. The only thing that seems to work is downgrading Vetur to 0.25.0.

## Reproducible Case

- Use latest Vetur on latest VS Code. Use something like Path Intellisense (doesn't matter) and try to import something by typing `import whatever from './'`.
- Expected result: Intellisense suggestion pops up right away.
- Actual result: After 10 seconds or so intellisense suggestion pops up.

### LINKED ISSUE #2192: Sometimes Vetur is still very slow
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.26.1
- VS Code version: 1.48.1

## Problem

I've seen related issues like https://github.com/vuejs/vetur/issues/1272 talking about calls to `synchronizeHostData`. I did not dig in too much, but I found that when validating sources and templates, calls such as `getSemanticDiagnostics` may call `synchronizeHostData` internally ([link](https://github.com/microsoft/TypeScript/blob/97a072926ffe2cb870732295fd3f0608e9a4e768/src/services/services.ts#L1504)), and by a rudimentary profiling it looks like each validation will took ~300ms on my computer. When I'm writing code, js and template will be validated separately, so they might take something like 500 or 600ms in total.
I'm not sure if that's the cause of the issue since I didn't do an accurate profiling, but probably it will help.
https://github.com/vuejs/vetur/blob/53ee52746b1f26f44391c3764bc7bd06d4ddaa46/server/src/modes/template/interpolationMode.ts#L72
https://github.com/vuejs/vetur/blob/2e32351514b01f3bec9478c0e55217e21b88d8ae/server/src/modes/script/javascript.ts#L118

### PR DESCRIPTION
**Pull request by yoyo930021**
Fixed #2192
Fixed #2163
Fixed #1731 

Reason: https://github.com/vuejs/vetur/issues/2192#issuecomment-706665715

### CODE REVIEW

**Comment by yoyo930021** [comment]
It seems to be the ultimate solution.
https://github.com/vuejs/vetur/issues/2192#issuecomment-708228473

Maybe this PR also can fix #2150

**Comment by Glandos** [comment]
1 week after applying manually this patch. No bug for me, and it solved the slowness.

**Review by octref — APPROVED** [review]
Very cool finding 🚀

**Comment by Stevenje** [comment]
@octref Great work are you going to push a release with this fix soon?

**Comment by yoyo930021** [comment]
> @octref Great work are you going to push a release with this fix soon?

It is in v0.29.0.

**Pull request merged**
