### PR TITLE
feat: added support for vuetify components

### LINKED ISSUE #380: Add framework support for Vuetify

### PR DESCRIPTION
**Pull request by nekosaur**
I hope everything looks okay. Modeled it after the previous PRs.

Closes #380

### CODE REVIEW

**Comment by octref** [comment]
It's fine for merging, but you didn't include any "documentation" keys for the tag/attr. I'm guessing you are auto-generating those files and meanwhile waiting for https://github.com/vuejs/vue/issues/7186 as a long-term solution?

**Comment by nekosaur** [comment]
You mean description? We have the text, we just need to do some work to match it up with the tags/attributes. So that will be next release of vuetify-helper-json

**Comment by octref** [comment]
Sounds good. Let us know when you have it so we can update the dependencies.

**Comment by sebastianmacias** [comment]
This is great, can you please post an example of how to use?

I have 0.11.6 installed, however when I try any of the [tags](https://github.com/vuetifyjs/vuetify-helper-json/blob/master/tags.json) it doesn't autocomplete them nor the attributes.

**Comment by octref** [comment]
Have vuetify as a dependency in your project and it should work automatically.

**Comment by sebastianmacias** [comment]
I have it

"vuetify": "^0.16.9" under "dependencies": {...} in my package,json however when I type v-app, v-ale.. nothing gets auto-completed.

**Comment by octref** [comment]
Emmet completion does not work with extra tags. You need to type `<v-app` etc to get suggestions. That is one of the current limitations.

**Comment by sebastianmacias** [comment]
@octref thanks for the tip. It's working like you said.

**Comment by Strum355** [comment]
Does this still work? I dont seem to get autocomplete for anything in *.vue <template> blocks

**Pull request merged**
