### PR TITLE
Use lodash to access config 

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
Vue language server should not assume too much vscode configuration.

Thank @Qquanwei pointing this out.

### CODE REVIEW

**Comment by octref** [comment]
Isn't it simpler to do everything in https://github.com/vuejs/vetur/blob/master/server/src/modes/script/javascript.ts#L67-L69?

Just assign the default settings to the config in each service.

**Comment by HerringtonDarkholme** [comment]
I don't think rehashing config in code is a good choice. Especially it is confusing that some options should differ from the ones in vetur. 

For example, `autoImport` is enabled by default in package.json. But it shouldn't be true for other editors by default since few of them implement `additionalTextEdit`. 

Idealistically, the configuration in VLS shall not highly coupled to one client, which is a situation LSP intend to solve at first. If the code base is ugly in handling option, it is just a reflection of the coupling.

**Comment by HerringtonDarkholme** [comment]
Another alternative is to define VLS' config in server package, and then Vetur can collect configuration in Code, transforming it to VLS' format.

We can reuse most part of `vetur` 's section, but prettier and stylus need additional works.

**Comment by octref** [comment]
I agree it's better to let VLS define a config it can accept, so it could have different default than Vetur's client default config.

**Pull request closed without merging**
