### PR TITLE
prettyhtml support .prettierrc

### PR DESCRIPTION
**Pull request by bolasblack**
Hi, I want to make prettyhtml in vetur to support .prettierrc (and prettyhtml cli does support .prettierrc https://github.com/Prettyhtml/prettyhtml/blob/6d253d9971ab8b32b3f23824c2581ccb6e18bff4/packages/prettyhtml/cli/args.js#L33)

But I have no idea about how to change the document https://github.com/vuejs/vetur/blob/master/docs/formatting.md#prettyhtml, and where is the unit test for `htmlFormat.ts`

So can anyone help me to improve this PR?

### CODE REVIEW

**Comment by bolasblack** [comment]
@octref Hi, can you help me?

**Comment by octref** [comment]
Hey I'm so sorry for the late response. Vetur already supports loading `.prettierrc` from this line: https://github.com/vuejs/vetur/blob/e21bc9cc5b3c82dd4447d86f870a00f05aba3c8f/server/src/utils/prettier/index.ts#L64.

If you still have issues please open new issues. Thanks!

**Comment by bolasblack** [comment]
@octref Hi, thanks for your reply.

Yes prettier config will load closest `.prettierrc`, but I found vetur use prettyhtml to format codes in `<template>` in vue file, and it not support this feature.

I tried add this feature to prettyhtml, but I found the config loading phase logic is written in [cli](https://github.com/Prettyhtml/prettyhtml/blob/c7c203521b9e87f18690e30ca5a9b413de918c5e/packages/prettyhtml/cli/index.js#L44), and vuter didn't use this part of the code.

So after thinking, I think I can add this function to vuter.

**Comment by octref** [comment]
Ohh I see, I'm sorry I misunderstood it.

**Comment by bolasblack** [comment]
Hi, I have resolved the conflicts

**Comment by octref** [comment]
Sorry for the very late turn around. Thanks for the PR!

**Comment by bolasblack** [comment]
@octref Cool! Thank you for the merging.

**Pull request merged**
