### PR TITLE
Change props validation, Fix #2141

### LINKED ISSUE #2141: Prop with `required: false` or default value should not trigger prop validation error when not provided
From https://github.com/vuejs/vetur/issues/2135#issuecomment-670841767

### PR DESCRIPTION
**Pull request by yoyo930021**
Fixed #2141

### CODE REVIEW

**Comment by octref** [comment]
For some reason rebase/merge all creates a lot of conflicts. Wanna open a new clean PR? I guess you were waiting for #2164 which I just merged.

**Comment by yoyo930021** [comment]
> For some reason rebase/merge all creates a lot of conflicts. Wanna open a new clean PR? I guess you were waiting for #2164 which I just merged.

This PR is waiting for #2164 and #2170 
It is not complete, and it is Draft.

**Comment by octref** [comment]
@yoyo930021 Just merged both. Go ahead.

**Comment by yoyo930021** [comment]
Replace by #2216

**Pull request closed without merging**
