### PR TITLE
Parallel VTI diagnostics

### PR DESCRIPTION
**Pull request by yoyo930021**
In my Macbook pro 13 2020, It's 10x faster.
The VTI can use in production when pairing up #2325 #2328

## gtime result
old:
834.59 user 29.64 system 11:21.12 elapsed 126% CPU (0avgtext+0avgdata 1409020maxresident)k

new:
0.26 user 0.12 system 1:47.03 elapsed 0% CPU (0avgtext+0avgdata 37980maxresident)k

### CODE REVIEW

**Comment by andrewisaburden** [comment]
@yoyo930021 

I tested on Ubuntu, and also #2328, and also combined both.

Old:
`1185.37user 16.35system 12:55.15elapsed 155%CPU (0avgtext+0avgdata 1034768maxresident)k`

#2329 only:
`0.16user 0.03system 2:20.26elapsed 0%CPU (0avgtext+0avgdata 40492maxresident)k`

#2328 only:
`1108.55user 15.17system 11:56.96elapsed 156%CPU (0avgtext+0avgdata 1024188maxresident)k`

Both #2329 #2328:
`0.20user 0.02system 2:15.25elapsed 0%CPU (0avgtext+0avgdata 40328maxresident)k`

The performance from #2329 is very nice, but #2328 seems quite minor (maybe non-existent, if there is variation from run to run).

Good work.

**Comment by yoyo930021** [comment]
> @yoyo930021
> 
> I tested on Ubuntu, and also #2328, and also combined both.
> 
> Old:
> `1185.37user 16.35system 12:55.15elapsed 155%CPU (0avgtext+0avgdata 1034768maxresident)k`
> 
> #2329 only:
> `0.16user 0.03system 2:20.26elapsed 0%CPU (0avgtext+0avgdata 40492maxresident)k`
> 
> #2328 only:
> `1108.55user 15.17system 11:56.96elapsed 156%CPU (0avgtext+0avgdata 1024188maxresident)k`
> 
> Both #2329 #2328:
> `0.20user 0.02system 2:15.25elapsed 0%CPU (0avgtext+0avgdata 40328maxresident)k`
> 
> The performance from #2329 is very nice, but #2328 seems quite minor (maybe non-existent, if there is variation from run to run).
> 
> Good work.

Thanks test.
Do you `yarn link vls` in vti when merging two PR and testing?

**Comment by andrewisaburden** [comment]
@yoyo930021 

I tried again:
`cd vetur`
`yarn && yarn compile`
`cd server`
`yarn link`
`cd vetur/vti`
`yarn link vls`
`yarn compile`

Then ran again:
`0.15user 0.05system 1:44.48elapsed 0%CPU (0avgtext+0avgdata 42360maxresident)k`

That's for both #2329 and #2328, so maybe the first time I missed a step (there is some improvement from ~2.15 to ~1.44).

Both looking good!

**Comment by yoyo930021** [comment]
> @yoyo930021
> 
> I tried again:
> `cd vetur`
> `yarn && yarn compile`
> `cd server`
> `yarn link`
> `cd vetur/vti`
> `yarn link vls`
> `yarn compile`
> 
> Then ran again:
> `0.15user 0.05system 1:44.48elapsed 0%CPU (0avgtext+0avgdata 42360maxresident)k`
> 
> That's for both #2329 and #2328, so maybe the first time I missed a step (there is some improvement from ~2.15 to ~1.44).
> 
> Both looking good!

This PR is violent.
Otherwise only #2328 , It should be twice as fast. 🤣

**Comment by yoyo930021** [comment]
I will close this PR.
First of all, this PR takes a lot of resources, and now we have a better way to do it.

I test a branch from merge #2328 and #2374 .
```
92.62user 3.35system 1:16.66elapsed 125%CPU (0avgtext+0avgdata 1169040maxresident)k
0inputs+0outputs (112major+688386minor)pagefaults 0swaps
```
It's an amazing result.

**Pull request closed without merging**
