### PR TITLE
Fixed Pug syntax highlighting error when concatenating strings

### LINKED ISSUE #1112: Pug Syntax Highlighting: String concatenation does not work inside vue directives
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux 
- Vetur version: 0.16.2
- VS Code version: 1.31.1

## Problem

String concatenation does not work inside vue directives when using different string literals (e.g. mixing `"` and `'`)

## Reproducible Case

```vue
<template lang="pug">
  .pug.javascript(:attr="i + will + 'concat' + this + string")
</template>
```

image

I will fix that as soon as possible.

### PR DESCRIPTION
**Pull request by Patcher56**
- will fix #1112 
- through reverting 58f72ee
- test throws errors but they were here since 0.16.2
- also added the issue template to the test files

### CODE REVIEW

**Comment by Patcher56** [comment]
Mentioned failing tests for travis ci in #1110 
The tests did only fail when vscode-test was downloaded the first time. The tests should work again now, but they are throwing errors which did not get fixed before release of 0.16.2.

**Comment by Patcher56** [comment]
Seems like the tests are exiting with code 0 although the test itself fails with code 1. @octref I think there has to be a review of the new test system. :smile:

**Comment by octref** [comment]
Fixed in https://github.com/vuejs/vetur/commit/ed2fa5bb093e2dfa0f9e300a20f92953bc00e8e2, can you do a rebase on master?

**Comment by Patcher56** [comment]
Sure, but I think my commit a4cc666 is still necessary. If you look into the travis log you see the Error where no path could be found.
This is because after downloading the vscode-test we are not passing a path to „runTests“.
My commit would fix that.

**Comment by octref** [comment]
Thanks for the quick fix. There's a build error. I'll merge and push changes to master.

Would you mind allowing me to push changes to the PRs you send in the future?

**Comment by Patcher56** [comment]
Thank you for the quick merge!
Yeah sure, that‘s no problem for me. Do I have to set sonme settings for this?

**Comment by octref** [comment]
Here's the checkbox: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Patcher56** [comment]
Ok got it, will check it next time.

**Pull request merged**
