### PR TITLE
Update eslint-plugin-vue to v5

### PR DESCRIPTION
**Pull request by armano2**
https://github.com/vuejs/eslint-plugin-vue/issues/697

i think vetur should also turn off some of rules, they are going to collide with prettier

### CODE REVIEW

**Comment by octref** [comment]
We use base and essential. So you are saying they are not recommended as default any more?

**Comment by armano2** [comment]
ahh, i was sure that you are using few more, but in that case it's all good

**Comment by armano2** [comment]
btw. no clue why but mac build failed

**Comment by michalsnik** [comment]
Hey @octref is there anything blocking this PR from being merged, except failing build that is rather not caused by this change?

**Comment by octref** [comment]
Nope, sorry. Will publish with new version soon.

**Pull request merged**
