### PR TITLE
fix: 🐛 https://github.com/vuejs/vetur/issues/2908

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
fixed https://github.com/vuejs/vetur/issues/2908

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
cc @yoyo930021

**Comment by IWANABETHATGUY** [comment]
`fileExtensionCompletion: false`

test1
`fileExtensionCompletion: true`

test2

**Comment by rchl** [comment]
Does it have to be an option. I think that the extension is always required for vue files since that's how webpack knows how to parse it. It is not required or recommended for javascript/typescript files though so I think that:
 - there should be no setting
 - the logic should be specific to vue files

**Comment by rchl** [comment]
Potentially the logic should be:
 - Skip extension for ts/js files
 - Add extension for any other type

**Comment by IWANABETHATGUY** [comment]
> Potentially the logic should be:
> 
> * Skip extension for ts/js files
> * Add extension for any other type  

finished

**Review by yoyo930021 — CHANGES_REQUESTED** [review]
The code is the right place to put it

https://github.com/vuejs/vetur/blob/4e54f396d9cafb1d7861ad8d17f8855fa635b07e/server/src/modes/script/javascript.ts#L252

**Review by yoyo930021 — APPROVED** [review]
LGTM, Thanks for your help.

**Pull request merged**
