### PR TITLE
support tsx

### LINKED ISSUE #325: JSX does not work with lang=ts
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Windows 10
- Vetur version: 0.9.0
- VSCode version: 1.13.1

## Problem

JSX does not work with `<script lang="ts">`.

image

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
Fix #325 

screenshot from 2017-07-15 21-34-52

Note this does not magically support JSX typing.

### CODE REVIEW

**Comment by rhyek** [comment]
@HerringtonDarkholme I assume this would be compatible with `vue-class-component`? If so, does that mean inside JSX I can still have type checking for all typescript things (global identifiers, class methods/properties, imported modules, etc)? I interpret 'does not magically support JSX typing` as it does not type check html things.

**Comment by HerringtonDarkholme** [comment]
@rhyek you're right. this pull request makes vetur recognize tsx syntax. So TS things get checked without tsx syntax error. HTML things won't get checked.

**Comment by rhyek** [comment]
Thanks! Sounds great.

**Comment by octref** [comment]
Looks good. Thanks!

**Pull request merged**
