### PR TITLE
Add support for analyzing vue-class-component and vue-property-decorator

### LINKED ISSUE #864: Go to definition not functioning from template in class-based typescript SFCs
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.12.6
- VS Code version: 1.25.1

## Problem

I'm uncertain whether this issue properly belongs to Vetur or to `vue-class-component`. It's strictly about the editor experience rather than transpiled output, so I thought it might be better here.

Vetur has some inconsistent `go to definition` behaviors which I've not seen documented. My setup here is `vue-cli@3.0.0-rc10`, `vue-class-component@6.0.0`, and `vue-property-decorator@7.0.0`.

Go to definition works on `<user-regristration />` in the following SFC:
``` html
<template>
  <user-registration />
</template>

<script lang="ts">
import Vue from 'vue';
import UserRegistration from './UserRegistration.vue';

export default Vue.extend({
  components: {
    UserRegistration
  }
})
</script>
```
but fails in the class based equivalent (`No definition found for 'user-registration'`):

``` html
<template>
  <user-registration />
</template>

<script lang="ts">
import Vue from 'vue';
import UserRegistration from './UserRegistration.vue';
import Component from 'vue-class-component';

@Component({
  components: {
    UserRegistration
  }
})
export default class TestComponent extends Vue {}
</script>

```

### LINKED ISSUE #1105: Support analyzing vue-class-component
Continuing #1083

`ComponentInfo` is not able to analyze `vue-class-component` yet.

The source looks like below, so it needs a different AST visitor. Maybe we can use typing from `vue-class-component` to analyze it.

```ts
@Component({
  props: {
    propMessage: String
  }
})
export default class App extends Vue {
  // initial data
  msg = 123

  // use prop values for initial data
  helloMsg = 'Hello, ' + this.propMessage

  // lifecycle hook
  mounted () {
    this.greet()
  }

  // computed
  get computedMsg () {
    return 'computed ' + this.msg
  }

  // method
  greet () {
    alert('greeting: ' + this.msg)
  }
}
```

### PR DESCRIPTION
**Pull request by yoyo930021**
Fixed #1105.
Fixed #864.

I want to support vue-property-decorator.
Reason:
1. Vue 3.0 isn't built-in class component. [rfc](https://github.com/vuejs/rfcs/pull/17)
2. vue-property-decorator is built-in vue-cli 3 typescript plugin.
3. [vue-typescript](https://github.com/itsFrank/vue-typescript)  project latest update was three years ago.

I'm not add test.
I will try to add.

### CODE REVIEW

**Comment by yoyo930021** [comment]
I will disappear for two weeks.
If this PR can help this project, You can edit it directly.

**Comment by yoyo930021** [comment]
I fixed the test error.

**Comment by antsteyer** [comment]
Please merge it

**Comment by qwqcode** [comment]
Please merge it!!

**Comment by Angeart** [comment]
Please merge it!!!!

**Comment by lbland94** [comment]
Testing locally, this appears to work perfectly for properties defined on the class. It does seem to exclude either `@Inject`ed properties or properties like `$route` defined by a vue plugin. Are those out of scope for this feature?

**Comment by yoyo930021** [comment]
@lbland94
The component data only has `props`,`data`,`computed` and `methods` by design in vetur.
I don't know where the `inject` data is placed. @octref 

The vue defined property isn't supported in template for now.

**Comment by antsteyer** [comment]
@yoyo930021 is it possible for you to publish your repo as VS Code extension ? So boring to not have this feature merged yet

**Comment by yoyo930021** [comment]
@antsteyer 
I think you can clone this PR by using it.

1. compile
```bash=
git clone https://github.com/yoyo930021/vetur.git
git checkout support-class-component
yarn
cd server && yarn && cd ..
yarn compile
```
2. set the vetur config to using it
vetur.dev.vlsPath set to `<projectUrl>/server` in vscode config.

PS. https://github.com/vuejs/vetur/blob/master/.github/CONTRIBUTING.md

**Comment by SaphuA** [comment]
I just tried out this branch and it's working quite well on first glance! Great work!

I'm using Vuex in combination with vuex-class-components and it seems this version of Vetur is unable to intellisence beyond "this.store", even though it displays the type correctly. Is this as expected or should this work as well?

**Comment by theoribeiro** [comment]
Is there a reason why this still wasn't merged or is it just due to maintainers' capacity?

**Comment by annnoo** [comment]
@SaphuA Got the same issue, but I guess this should get fixed :( I could maybe take a look, but I've never done any vscode extension development and I don't think I am able to fix this

**Comment by yoyo930021** [comment]
@SaphuA @annnoo I think #1446 can fix it.

**Comment by ZhengXiaowei** [comment]
wasn't merged ? how to solve this problem? complie this branch?

**Comment by yoyo930021** [comment]
https://github.com/vuejs/vetur/pull/1323#issuecomment-531542303

**Comment by ZhengXiaowei** [comment]
> [#1323 (comment)](https://github.com/vuejs/vetur/pull/1323#issuecomment-531542303)

thx, it's work great

**Comment by AlaaZorkane** [comment]
Any news on this?

**Comment by dennis2k** [comment]
I am not able to get support-class-component branch workaround to work. So this merge would be epic

**Comment by yoyo930021** [comment]
Give the maintainer some time.
I believe it's coming.

**Comment by braivre** [comment]
How can I test this locally? yoyo guide doesn't seems to work anymore... almost a year and still nothing :(

**Comment by yoyo930021** [comment]
> How can I test this locally? yoyo guide doesn't seems to work anymore... almost a year and still nothing :(

https://github.com/vuejs/vetur/pull/1323#issuecomment-531542303

**Comment by yoyo930021** [comment]
Hi anyone, I publish self-maintenance vscode extension.
This extension will be maintained until Vetur is reactivated.

https://marketplace.visualstudio.com/items?itemName=yoyo930021.vuter

**Comment by octref** [comment]
Rebased and updated dependencies. Want to take a look at the test failures? Likely related to updated TS version.

**Comment by yoyo930021** [comment]
@octref Oh I know.
It's wrong tests about kind when we use typescript info.

**Comment by yoyo930021** [comment]
Also fixed #864

**Comment by tjhiggins** [comment]
@yoyo930021 will this also work for https://github.com/nuxt-community/nuxt-property-decorator?

**Comment by yoyo930021** [comment]
> @yoyo930021 will this also work for https://github.com/nuxt-community/nuxt-property-decorator?

I don't know this library existed.
I don't think there's anything wrong with a quick scan.

**Comment by aziztitu** [comment]
When using the Emit decorator, I get this weird issue when providing an inline event callback in the template.

Here's how the event is declared using Emit decorator:
```
@Component()
export default class LeaveApplicationForm extends Vue {
  @Emit()
  private onSubmit() {
    this.reset();
    return;
  }
}
```

And this is how I'm providing the event callback in the template:
```
<LeaveApplicationForm
  @on-submit="showLeaveApplicationDialog = false"    // If I pass a function here, the error disappears
>
</LeaveApplicationForm>
```

And this is the error I get:
```
(property) 'on-submit'?: (($event: any) => (arg: undefined) => any) | undefined

Type 'typeof "on-submit"' is not assignable to type '($event: any) => (arg: undefined) => any'.
  Type '"on-submit"' is not assignable to type '(arg: undefined) => any'.
    Type '"on-submit"' provides no match for the signature '(arg: undefined): any'.Vetur(2322)
```

Note: This error does not show up if I pass a function as the callback instead. 

I think the reason is that when using the Emit decorator, the type of the event is being recognized as `(($event: any) => (arg: undefined) => any) | undefined`. 
But it should be something like `($event: any) => void` or `($event: any) => CallableFunction | undefined`

Not quite sure if the issue is with Vetur or the vue-property-decorator library.

Does anyone else have this same issue?

**Comment by yoyo930021** [comment]
> When using the Emit decorator, I get this weird issue when providing an inline event callback in the template.
> 
> Here's how the event is declared using Emit decorator:
> 
> ```
> @Component()
> export default class LeaveApplicationForm extends Vue {
>   @Emit()
>   private onSubmit() {
>     this.reset();
>     return;
>   }
> }
> ```
> 
> And this is how I'm providing the event callback in the template:
> 
> ```
> <LeaveApplicationForm
>   @on-submit="showLeaveApplicationDialog = false"    // If I pass a function here, the error disappears
> >
> </LeaveApplicationForm>
> ```
> 
> And this is the error I get:
> 
> ```
> (property) 'on-submit'?: (($event: any) => (arg: undefined) => any) | undefined
> 
> Type 'typeof "on-submit"' is not assignable to type '($event: any) => (arg: undefined) => any'.
>   Type '"on-submit"' is not assignable to type '(arg: undefined) => any'.
>     Type '"on-submit"' provides no match for the signature '(arg: undefined): any'.Vetur(2322)
> ```
> 
> Note: This error does not show up if I pass a function as the callback instead.
> 
> I think the reason is that when using the Emit decorator, the type of the event is being recognized as `(($event: any) => (arg: undefined) => any) | undefined`.
> But it should be something like `($event: any) => void` or `($event: any) => CallableFunction | undefined`
> 
> Not quite sure if the issue is with Vetur or the vue-property-decorator library.
> 
> Does anyone else have this same issue?
> 
> How does Vetur find the type of the events?
Please open a new issue.

**Pull request merged**
