### PR TITLE
Follow user's config while resolving autoImport path, related #1177

### PR DESCRIPTION
**Pull request by hikerpig**
Same as #1177 , I prefer getting absolute path with the auto-import feature. So I dive into the codebase and found these related code.

My modification goes a little further, I think it is best to follow user's preferences on js/ts language features.

## Pitfall

If the js/ts preferences are changed after vetur is loaded, this `config` seemed to fail to update ? I think it's a more common problem, but I am not an expert on this, so some help is needed.

### CODE REVIEW

**Comment by credred** [comment]
I have this problem after adding `"typescript.preferences.importModuleSpecifier": "non-relative"` on `settings.json` file.

**Comment by yoyo930021** [comment]
The link is code about VSCode implementation.
https://github.com/microsoft/vscode/blob/508f43166bd8551a26d3b53b2e04008d0b9c357c/extensions/typescript-language-features/src/features/fileConfigurationManager.ts#L177

There are other places to use user preferences,
and then we need to delete the conflict Vetur config.
https://github.com/vuejs/vetur/pull/1352#issuecomment-509900249

**Comment by yoyo930021** [comment]
I plan to fork this project and maintain until this project reactivate.
Maybe fixed it or merge this PR for fork project.

**Comment by hikerpig** [comment]
@yoyo930021  Nice hints, thanks, will definitely take a look.

And about forking this project, I've already done it and released a [personal version](https://marketplace.visualstudio.com/items?itemName=hikerpig.vetur) that has your PR merged in. Thumbs up for your work 💯 .

**Comment by yoyo930021** [comment]
> @yoyo930021 Nice hints, thanks, will definitely take a look.
> 
> And about forking this project, I've already done it and released a [personal version](https://marketplace.visualstudio.com/items?itemName=hikerpig.vetur) that has your PR merged in. Thumbs up for your work 💯 .

I try to fork project and find some test problem. #1323

**Comment by hikerpig** [comment]
> > @yoyo930021 Nice hints, thanks, will definitely take a look.
> > And about forking this project, I've already done it and released a [personal version](https://marketplace.visualstudio.com/items?itemName=hikerpig.vetur) that has your PR merged in. Thumbs up for your work 💯 .
> 
> I try to fork project and find some test problem. #1323

Yes, mostly in interpolation LSP tests. But I have used the personal version daily for months and it worked fine.

After the release I see it would be better to fix those test failures. Still looking into it, haven't found a clue yet (since recently I'm a little busy with new work 😢 ).

**Comment by octref** [comment]
@yoyo930021 I opened #2109. We should gradually make the js/ts integration to follow all js/ts settings.

@hikerpig Thanks for your fix 👍

**Pull request merged**
