### PR TITLE
add component name settings

### PR DESCRIPTION
**Pull request by dimensi**
Hi, I do not know about the others, but I call all custom components via PascalCase, but I can’t get hints in the template in the PascalCase either, so I added this additional setting. I would also like to finish the test, but I cannot understand how to customize the settings in the tests.
I also want remove strange Vue suffix in auto imports, but can't understand how.
ezgif com-video-to-gif

### CODE REVIEW

**Comment by octref** [comment]
Here is an end-to-end test https://github.com/vuejs/vetur/blob/master/test/e2e.sh

You can add settings here, in `.vscode/settings.json`: https://github.com/vuejs/vetur/tree/master/test/fixture

**Comment by dimensi** [comment]
@octref i can't start e2e tests, i got same error on mac os and ubuntu 18.
```
### VS Code Extension Test Run ###
Current working directory: /home/dimensi/projects/vetur
Running extension tests: /home/dimensi/projects/vetur/.vscode-test/stable/VSCode-linux-x64/code /home/dimensi/projects/vetur/test/fixture --extensionDevelopmentPath=/home/dimensi/projects/vetur --extensionTestsPath=/home/dimensi/projects/vetur/dist/test
[main 1:01:10 AM] Running extension tests from the command line is currently only supported if no other instance of Code is running.

[main 1:01:10 AM] Error: Running extension tests from the command line is currently only supported if no other instance of Code is running.
    at /home/dimensi/projects/vetur/.vscode-test/stable/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:545:1012
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

module.js:545
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/dimensi/projects/vetur/.vscode-test/stable/VSCode-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/home/dimensi/projects/vetur/.vscode-test/stable/VSCode-linux-x64/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/dimensi/projects/vetur/.vscode-test/stable/VSCode-linux-x64/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:383:26)
```

**Comment by octref** [comment]
@dimensi Thanks a lot for working on it! You need to either:

- Use the Insiders version: https://code.visualstudio.com/insiders/ for writing the code
- Close all VS Code Stable instances and run the test from CLI

The E2E test can't be run when VS Code Stable is open.

**Comment by dimensi** [comment]
I close it, because you release same feature.

**Comment by octref** [comment]
@dimensi Sorry about that, the component analysis part was not well done so I had to rewrite it.

**Comment by dimensi** [comment]
Don't worry, i don't know your project like you. Thx for feature.

**Pull request closed without merging**
