### PR TITLE
Refactor to setupConfigure for #2388

### LINKED ISSUE #2388: Vetur auto formatting not working on .vue files until disabled and then re-enabled in preferences
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS Catalina
- Vetur version: 0.28.0
- VS Code version: 1.50.1

## Problem
After launching VSCode, Vetur does not format .vue files until going into vscode preferences > extensions > vetur > toggle `Enable/Disable the Vetur document formatter` off and then on again.  After toggling, it works as expected.
Output from panel, both before and after toggling the mentioned setting so it appears Vetur is loaded when VSCode launches:
```
Loaded bundled typescript@4.0.2.
Vetur initialized
```

## Reproducible Case

Unsure how I can reproduce this, but there is at least one other user on the Discord vueland eslint channel who has the same/similar problem.

### PR DESCRIPTION
**Pull request by yoyo930021**
Fixed #2388 

It also conveniently fixes a problem where incorrect settings could be imported.

### CODE REVIEW

**Review by octref — APPROVED** [review]
LGTM 👍

**Comment by rchl** [comment]
I'd like to better understand the changes done here to fix it properly in #2436.

Why was it not enough to run `setupDynamicFormatters()` from `onDidChangeConfiguration` notification?

Sending it when handling `initialize` request is too early.

We could send it from `initialized` but I'm not sure why from `onDidChangeConfiguration()` was not enough since the client is pretty much guaranteed to send it early after initialize.

Was the problem more related to passing a partial config to `setupDynamicFormatters`?

**Comment by yoyo930021** [comment]
> I'd like to better understand the changes done here to fix it properly in #2436.
> 
> Why was it not enough to run `setupDynamicFormatters()` from `onDidChangeConfiguration` notification?
> 
> Sending it when handling the `initialize` request, as done here, is too early.
> 
> We could send it from `initialized` but I'm not sure why from `onDidChangeConfiguration()` was not enough since the client is pretty much guaranteed to send it early after initialize.
> 
> Was the problem more related to passing a partial config to `setupDynamicFormatters`?

I think it's a try.
My first suspicion was that it wouldn't be triggered `onDidChangeConfiguration` on startup.
I guess we could rollup back this part.

**Comment by rchl** [comment]
OK, good. That means I can safely revert that logic. Thanks.

**Pull request merged**
