### PR TITLE
Try adding yarn cache to CI

### PR DESCRIPTION
**Pull request by octref**

### CODE REVIEW

**Comment by yoyo930021** [comment]
Add `yarn config set cache-folder '$(Pipeline.Workspace)/.yarn'`?

**Comment by octref** [comment]
> Add yarn config set cache-folder '$(Pipeline.Workspace)/.yarn'?

Good point, will try.

But I'm now doubting if we should use cache, restoring .vscode-test (~200MB) takes 7 minutes:

image

**Comment by octref** [comment]
I didn't realize the variable `YARN_CACHE_FOLDER` is used by `yarn` as well...Thought it's only for simplifying the bash script.

**Comment by octref** [comment]
Seems much faster now:

image

**Pull request merged**
