### PR TITLE
Allows you to increase the file extension associated with the language.

### PR DESCRIPTION
**Pull request by zhetengbiji**

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thank you for contribution.

May I ask in which way do you need this feature? Thanks.

**Comment by zhetengbiji** [comment]
Some frameworks for developing [WeChat mini programs](https://mp.weixin.qq.com/debug/wxadoc/dev/index.html) are based on "Vue" development but do not use the ".vue" extension. When using these frameworks, even if "files.associations" is configured in vscode, some functions of "vetur" are not normal. These frameworks are: [minimal-CLI](https://github.com/meili/min-cli),[wepy](https://github.com/Tencent/wepy).

**Comment by HerringtonDarkholme** [comment]
Hi @zhetengbiji. As you have said, this change is for other frameworks. I don't know how much they are stray from Vue. I'm quite worried about that even if adding extensions are not enough to support them. Or users have more feature request for more frameworks.

@octref any idea?

**Comment by HerringtonDarkholme** [comment]
For your specific usage, please read: 
https://tencent.github.io/wepy/document.html#/?id=wepyconfigjs%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6%e8%af%b4%e6%98%8e

also 
https://github.com/Tencent/wepy/issues/529#issuecomment-345123157

and 

https://github.com/Tencent/wepy/issues/856#issuecomment-361172404

**Comment by octref** [comment]
I don't know wechat mini program that well. Just because it looks like Vue doesn't mean all the language features are the same as Vue.
Ideally support for it should be done in a separate extension. Feel free to take code, fork or ask questions. Currently I don't have time for it.

**Pull request closed without merging**
