### PR TITLE
update tslint config

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
@octref any suggestion?

**Comment by octref** [comment]
I saw you were still pushing commits so I thought you were not done yet.

Took a rough look but looks fine. Would prettier-ed output be consistent with the current tslint setiting?

**Comment by HerringtonDarkholme** [comment]
I have completed this pull request. Other tslint config seems too strict for me (e.g. import order).

I have checked prettier's default option. This setting is compatible.

**Comment by octref** [comment]
Sounds good. Thanks!

**Pull request merged**
