### PR TITLE
proper fix quoteless value

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
@octref 

screen shot 2018-01-17 at 11 07 43 am

### CODE REVIEW

**Comment by octref** [comment]
Umm...We wouldn't get the value as `source.js`, and I don't know if there is a good fix for that.

**Comment by HerringtonDarkholme** [comment]
> get the value as source.js

This would require us implement half of custom JavaScript syntax highlight. Only `'<>=" ` is not allowed in bare attribute value. So technically users can write like 
```ts
:bind={[named]:long.syntax[0](a*b).test(/regex/)?#futurePrivateField:ternary}
```

Sensible usage should always quote html value IMHO. I don't think syntax highlight can cover all use case. If user does write something awful in one place, let that place get less highlighted. 

But we do need to improve current implementation, since one bad usage will ruin all following highlighting.

**Comment by HerringtonDarkholme** [comment]
@octref  any further action?

**Comment by octref** [comment]
This only fixes it for v-directives, I'm guessing we want quoteless attributes for general attributes (`tag-id-attributes`) as well.

**Comment by HerringtonDarkholme** [comment]
I have updated vue-html.yaml. However, sublime text gives me a lot of unnecessary diff.

Would you like to generate the json on your side? @octref

**Comment by octref** [comment]
I tried regenerating the grammar. Same thing...seems Sublime changed its way of organizing the grammar. Just go ahead and regenerate it.

I also tried pushing to `HerringtonDarkholme/vetur:master` but got the permission denied error. Never figured out how to make small changes to other PRs on GitHub...

**Pull request merged**
