### PR TITLE
chore: update the prettyhtml version to 0.8.4

### PR DESCRIPTION
**Pull request by xiaomingplus**
for resolve following issues:
<https://github.com/Prettyhtml/prettyhtml/pull/71>
<https://github.com/Prettyhtml/prettyhtml/pull/73>
<https://github.com/Prettyhtml/prettyhtml/pull/75>

1. use tabWidth config for indent script and style tag
2. fix weex component image tag format error 
3. Use snapshot testing,Rerun on tested output to ensure that the formatter is stable.Fix editorconfig to ignore fixtures

and I also changed the format expected result , here is the discuss with prettyhtml author:<https://github.com/Prettyhtml/prettyhtml/issues/74>

thanks~

### CODE REVIEW

**Comment by xiaomingplus** [comment]
I think All checks have passed :)

**Comment by octref** [comment]
Looking good. Thanks!

**Comment by xiaomingplus** [comment]
@octref ,thanks,May I know when the vetur publish to  the vscode market?

**Comment by octref** [comment]
I'm looking through PRs and will publish one either later today or tomorrow morning.

**Pull request merged**
