### PR TITLE
fix: cannot read property 'completion' of undefined

### PR DESCRIPTION
**Pull request by Qquanwei**
Some editor will be broken lsp-server by this error.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks!

May I ask what editor do you use?

**Comment by Qquanwei** [comment]
:+1: 
 I use Emacs and `lsp-vue` .

**Comment by HerringtonDarkholme** [comment]
It's great to see LSP is adopted by extensive editors!

Have you encountered issues in using vls? It is mainly target for vscode but I want to make it acceptable universally. 

~~I used it in Vim and emmet snippets are quite annoying~~

**Comment by octref** [comment]
@Qquanwei Umm...I'm not sure if this is the right fix. If `config.vetur` can be null there are many other places this would cause an error. So for Emacs it does not read the default config of Vetur (https://github.com/vuejs/vetur/blob/master/package.json#L125-L287) when there is none?

**Comment by Qquanwei** [comment]
@octref you are right. This also because lsp-vue not implement default config.

**Pull request merged**
