### PR TITLE
Fix intellisense and other features when open multiple files

### LINKED ISSUE #1449: Intellisense / type checking stopped working in v0.22.4
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 x64
- Vetur version: 0.22.4
- VS Code version: 1.38.1
- Already reinstalled Visual Studio Code, Vetur
- Happens on multiple PC
- Tried to remove other plugins

## Problem

Intellisense stopped working properly in Vue files. Although it works in the first opened vue file or if it was opened in the previous session.
Downgrading to Vetur 0.22.3 fixed the issue.

## Reproducible Case

1. Close all tabs in the current project
2. Close and open Visual Studio Code
3. Open a vue file
4. Wait until the plugins are loaded
5. Hovering over/Ctrl+space at imported objects, variables doesn't show any info
6. Close and open Visual Studio Code
7. Intellisense works in the previously opened file

### PR DESCRIPTION
**Pull request by yoyo930021**
Fix #1449

### CODE REVIEW

**Comment by yoyo930021** [comment]
@octref
This is a critical bug.
Please handle it quickly.

**Comment by yoyo930021** [comment]
Linux pass test in Travis CI.
macOS pass in Azure CI.

**Comment by sploders101** [comment]
I'm not sure the Vetur-CI failing has to do with anything introduced by this PR. It looks like npm is complaining about its lock file and a cached dependency not matching up, but this PR doesn't modify package.json or the lockfile. Regardless, it should be looked into, but lots of people are waiting on this critical bug-fix, so please don't dismiss it due to that test.

I'm not sure how azure CI works, but you could try deleting the npm cache, or deleting and recreating the lockfile, or both.

**Comment by yoyo930021** [comment]
This test is pass.
Two CI is same test case and environment.

I think author in the vacation.

**Comment by octref** [comment]
Thanks for the fix and sorry for the late response. I was traveling.

**Pull request merged**
