### PR TITLE
prefer file local prettier

### PR DESCRIPTION
**Pull request by maeldur**
I brought in the [file from prettier-vscode](https://github.com/prettier/prettier-vscode/blob/master/src/requirePkg.ts) to have vetur [behave the same way as that extension](https://github.com/prettier/prettier-vscode#prettier-resolution)   

I've tested this change with no prettier, an older version of prettier, and a newer one and it seems to work ok.. is there more formal testing i should do?

### CODE REVIEW

**Comment by maeldur** [comment]
Btw, thanks for the awesome extension and really appreciate the work you did in #873! hopefully this takes us to 1/15 😄

**Comment by octref** [comment]
Sorry for the late response. Mostly look good. Once you make the requested changes I'll pull it in.

**Comment by maeldur** [comment]
Hi @octref, changes made.

re: copyright, I added an entry into ThirdPartyNotices with the LICENSE from prettier-vscode. is that what you meant?  If not, let me know if there's something else I can do.

**Comment by octref** [comment]
@maeldur Thanks for adding it to the ThirdPartyNotice. In the `requirePkg.ts` file's top, please also include something like (use `y` to permalink to the file in a specific commit)

```ts
/**
 * Adapted from https://github.com/prettier/prettier-vscode/blob/1843acb5defac7898862a1df61cb67c7a8355d69/src/requirePkg.ts
 */
```

**Comment by maeldur** [comment]
@octref thanks for the review - added. i went 9 digits into the sha for the blob but if you prefer the long one i'll use the whole thing.

**Comment by octref** [comment]
Thanks again. I just made a release. I'll try to bring in prettyhtml and make a new release again.

**Pull request merged**
